# Generated by Django 3.2.20 on 2023-07-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20230706_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(default='', upload_to='listings/'),
            preserve_default=False,
        ),
    ]
