# Generated by Django 3.2.20 on 2023-07-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='logo',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='logo',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
