# Generated by Django 3.2.20 on 2023-07-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20230707_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='logo',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='language',
            name='logo',
            field=models.TextField(),
        ),
    ]
