# Generated by Django 3.2.20 on 2023-08-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20230803_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
