# Generated by Django 3.2.20 on 2023-08-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_project_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='gitHubLink',
        ),
        migrations.AddField(
            model_name='project',
            name='viewsLink',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
