# Generated by Django 3.2.20 on 2023-08-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20230804_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='grandeDescription',
            new_name='bigDescriptioneDescription',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='langage',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='petiteDescription',
            new_name='littleDescription',
        ),
    ]
