# Generated by Django 3.2.20 on 2023-08-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20230804_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='littleDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='bigDescriptioneDescription',
            new_name='features',
        ),
    ]
